### ISSUE TITLE
Set ENS reverse registrar for elimu.dao.eth

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/web3-wiki#19]
https://etherscan.io/address/0xa58e81fe9b61b5c3fe2afd33cf304c454abfc7cb#writeContract#F7

**Comment by Bender-22** [comment]
@nya-elimu Executed: https://etherscan.io/tx/0xe33b24f41582e9ef2aea1258757c2c777230cad9cb028dd2a321502f3b29dd10
