### ISSUE TITLE
Create Dapp for linking sponsors with distributors

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/web3-wiki#23]
Build a system for sponsoring the education of one individual child.

- Smart contract for receiving payment from sponsor (denominated in [`$ELIMU`](https://etherscan.io/token/0xe29797910d413281d2821d5d9a989262c8121cc2) tokens?).
- UI for a sponsor to transfer payment.
- UI for a distributor to initiate distribution.
- Smart contract for paying distributor for installing software & transporting hardware.
- UI for sponsor to see distribution updates.
- UI for distributor to submit proof of delivery and getting paid.

**Comment by nya-elimu** [comment]
https://github.com/orgs/elimu-ai/projects/12
