### ISSUE TITLE
Adjust drip list funding splits (by Thu 2024-07-25)

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/web3-wiki#31]
https://github.com/elimu-ai/web3-wiki/blob/main/DRIP_LIST_FUNDING_SPLITS.md

- [x] Content Creation 🎶🎙️
    ✔️ [Hindi](https://www.drips.network/app/drip-lists/44233954899343831995062217275215737681377860849646413826815741964160): [off-chain](https://github.com/elimu-ai/web3-wiki/commit/67f11c5c00824c36bc056701a83308ec3f736f20) | [on-chain](https://etherscan.io/tx/0x3bcb7910df849a1ebcae2cf50d74bd719393bedafd7930b3080a4a0fe2d6e00d)
    ✔️ [Tagalog](https://www.drips.network/app/drip-lists/44233954899343831995062217275215737681377860849646413826815741964163): [off-chain](https://github.com/elimu-ai/web3-wiki/blob/main/funding-splits/content/FUNDING_SPLITS_TGL.csv) | [on-chain](https://etherscan.io/tx/0xe9c2c0e2fe3013831950c5c98505a9b8a5ed080f31e720b24bf45587652fc550)
- [x] Engineering & AI/ML 👩🏽‍💻📱
    ✔️ [webapp](https://www.drips.network/app/projects/github/elimu-ai/webapp): [off-chain](https://github.com/elimu-ai/webapp/commit/cee00d9b87c44f8ea62a201d32d2eca4b2a7c022) | [on-chain](https://etherscan.io/tx/0xa0b91897b6f31a066953ad65565d9cac6ce0ab3486b392ca0c225ab84345b933)
- [x] Distribution & Data Collection 🛵💨
    ✔️ [website](https://www.drips.network/app/projects/github/elimu-ai/website): [off-chain](https://github.com/elimu-ai/website/commit/cfa3f3e3d1df8d6dde2b6c4246dcfd7b6240ef6a) | [on-chain](https://etherscan.io/tx/0x5aec89703feebc74e29847651396af437edf159b0ba58889e770c530c9dcccc7)

**Comment by charanbhatia** [comment]
@nya-elimu can you assign this issue to me?

**Comment by nya-elimu** [comment]
@charanbhatia This issue has been closed already.
